server:
  port: 6376
  address: 0.0.0.0
  ssl:
    key-store: classpath:3768539_www.xizhique.com.pfx
    key-store-password: S0JNuaJU
    key-store-type: PKCS12

spring:
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.187.145:3306/dh-resume?serverTimezone=GMT%2B8
    username: root
    password: 10e9074341007840
  redis:
    host: 127.0.0.1
    port: 6379
    testOnBorrow: true
  thymeleaf: 
    prefix: classpath:/static/
    
logging:
  pattern:
    console: "%d - %msg%n"
  file: /www/wwwroot/logs/dh-resume.log
#spring 扫描实体类路径
mybatis:
  type-aliases-package: com.resume.api.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus.mapper-locations: classpath*:mapper/*.xml
mybatis-plus.type-aliases-package: com.resume.api.entity
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

