server:
  port: 8088

spring:
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dh-resume?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf: 
    prefix: classpath:/static/
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    suffix: .html
    templateEncoding: UTF-8
    templateLoaderPath: E:\\
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
#spring 扫描实体类路径
mybatis:
  type-aliases-package: com.resume.api.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus.mapper-locations: classpath*:mapper/*.xml
mybatis-plus.type-aliases-package: com.resume.api.entity
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#文件路径配置
PDF:
  DEST: E:\\
  HTML: E:\\
  FONT: E:\\simhei.ttf
file:
  img: E:\\
WeiXin:
  appId: wx370c238bee33c668
  appSecret: 79306d329b2248f4ae6d6733311b27cd